spring:
    application:
        name: slack

    # PostgreSQL設定
    datasource:
      url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      username: ${PGUSER}
      password: ${PGPASSWORD}

    # Hibernate設定
    jpa:
      hibernate.ddl-auto: create-drop
      properties.hibernate:
        hbm2ddl.auto: create
        format_sql: true
        #dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      open-in-view: false

logging.level:
  com:
    slack:
      api: DEBUG
      api.bolt: DEBUG

server:
  port: 3000
